CREATE TABLE health (
                        id BIGINT PRIMARY KEY NOT NULL,
                        status VARCHAR (255)

);

INSERT INTO health VALUES (1001, 'Good'),
                          (1002,'Good'),
                          (1003,'Bad'),
                          (1004,'Ok'),
                          (1005,'Good'),
                          (1006,'Bad'),
                          (1007,'Ok'),
                          (1008,'Good'),
                          (1009,'Bad'),
                          (1010,'Ok'),
                          (1011,'Good'),
                          (1012,'Bad'),
                          (1013,'Ok'),
                          (1014,'Good'),
                          (1015,'Bad'),
                          (1016,'Ok'),
                          (1017,'Good'),
                          (1018,'Bad'),
                          (1019,'Ok'),
                          (1020,'Good'),
                          (1021,'Bad'),
                          (1022,'Ok'),
                          (1023,'Good'),
                          (1024,'Bad'),
                          (1025,'Good'),
                          (1026,'Bad'),
                          (1027,'Ok'),
                          (1028,'Good'),
                          (1029,'Bad'),
                          (1030,'Ok'),
                          (1031,'Good'),
                          (1032,'Bad'),
                          (1033,'Ok'),
                          (1034,'Good'),
                          (1035,'Bad'),
                          (1036,'Ok'),
                          (1037,'Good'),
                          (1038,'Bad'),
                          (1039,'Ok'),
                          (1040,'Good'),
                          (1041,'Bad'),
                          (1042,'Ok'),
                          (1043,'Good'),
                          (1044,'Bad'),
                          (1045,'Ok'),
                          (1046,'Good'),
                          (1047,'Bad'),
                          (1048,'Ok'),
                          (1049,'Good'),
                          (1050,'Bad'),
                          (1051,'Ok');